### ISSUE TITLE
oneflow-27测试数据

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-glm#18]
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [使用环境](#%E4%BD%BF%E7%94%A8%E7%8E%AF%E5%A2%83)
- [条形图](#%E6%9D%A1%E5%BD%A2%E5%9B%BE)
  - [batch-24 数据结果](#batch-24-%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%9C)
  - [batch-16数据结果](#batch-16%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%9C)
  - [batch-8 数据结果](#batch-8-%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%9C)
  - [小结](#%E5%B0%8F%E7%BB%93)
- [数据表](#%E6%95%B0%E6%8D%AE%E8%A1%A8)
  - [使用 batch-size=24 测试](#%E4%BD%BF%E7%94%A8-batch-size24-%E6%B5%8B%E8%AF%95)
    - [BaseLine1（Pytorch FP16）](#baseline1pytorch-fp16)
    - [BaseLine1（Pytorch FP32）](#baseline1pytorch-fp32)
    - [OneFlow（Graph FP16）](#oneflowgraph-fp16)
    - [OneFlow（Graph FP32）](#oneflowgraph-fp32)
    - [OneFlow（eager FP32）](#onefloweager-fp32)
  - [使用 batch-size=16 测试](#%E4%BD%BF%E7%94%A8-batch-size16-%E6%B5%8B%E8%AF%95)
    - [BaseLine1（Pytorch FP16）](#baseline1pytorch-fp16-1)
    - [BaseLine1（Pytorch FP32）](#baseline1pytorch-fp32-1)
    - [OneFlow（Graph FP16）](#oneflowgraph-fp16-1)
    - [OneFlow（Graph FP32）](#oneflowgraph-fp32-1)
    - [OneFlow（eager FP32）](#onefloweager-fp32-1)
  - [使用 batch-size=8 测试](#%E4%BD%BF%E7%94%A8-batch-size8-%E6%B5%8B%E8%AF%95)
    - [BaseLine1（Pytorch FP16）](#baseline1pytorch-fp16-2)
    - [BaseLine1（Pytorch FP32）](#baseline1pytorch-fp32-2)
    - [OneFlow（Graph FP16）](#oneflowgraph-fp16-2)
    - [OneFlow（Graph FP32）](#oneflowgraph-fp32-2)
    - [OneFlow（eager FP32）](#onefloweager-fp32-2)

# 使用环境

1. oneflow版本：2023.01.06 编译  c376b8fbf4 (HEAD -> master)
2. flow.__version__ = '0.8.1+cu117.git.c376b8fbf4'
3. torch.__version__ '1.13.0+cu117'
4. export NVIDIA_TF32_OVERRIDE=0
5. 机器 oneflow27-root（NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7 
GPU 3090Ti 显存 24GB）
# 条形图
## batch-24 数据结果
<div>
  <a href="https://oneflow-static.oss-cn-beijing.aliyuncs.com/one-yolo/document/batch_24.html"> 
  <img src="https://user-images.githubusercontent.com/109639975/211199972-1498dacb-ebcf-49eb-93ca-e5cba29b1e4b.png"
  </a>
</div>

## batch-16数据结果

<div>
<a href="https://oneflow-static.oss-cn-beijing.aliyuncs.com/one-yolo/document/batch_16.html">
<img src="https://user-images.githubusercontent.com/109639975/211200026-ea076e5f-e979-418f-8a79-d68e395eaae4.png">
</a>
</div>

## batch-8 数据结果

<div>
<a href="https://oneflow-static.oss-cn-beijing.aliyuncs.com/one-yolo/document/batch_8.html">
<img src="https://user-images.githubusercontent.com/109639975/211200260-0253bcd9-986f-45df-8ba5-b753ba79d24f.png">
</a>
</div>

## 小结
- 单机单卡：
在 fp16模式下：batch-size增加one-glm优势下降。
![image](https://user-images.githubusercontent.com/109639975/211229196-98407064-1f34-458e-8bbe-3abb1cea5a1e.png)
![image](https://user-images.githubusercontent.com/109639975/211229234-9d0bab1a-f1cb-486b-82d7-f30d212954a3.png)
![image](https://user-images.githubusercontent.com/109639975/211229240-ec10df81-1bf1-435b-91c5-97cfc2f2a658.png)

- 单机多卡：batch-size增加one-glm优势下降。
![image](https://user-images.githubusercontent.com/109639975/211229368-c54db34e-af30-41f9-b446-1bf18eee6ac4.png)
![image](https://user-images.githubusercontent.com/109639975/211229376-e4a9482b-9352-447f-9951-1fc8f525512d.png)
![image](https://user-images.githubusercontent.com/109639975/211229379-e99215bf-ad33-4555-a24d-f2b64f3fbcb7.png)
# 数据表

### BaseLine1（Pytorch FP16）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度            | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|---------------------|--------------|------------|----------|
| Eager单卡    | 24         | 236.45(samples/s)   | 18909MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 24         | 443.41(samples/s)   | 21217MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 24         | 771.10 (samples/s)  | 22007MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 24         | 1566.29 (samples/s) | 20223MiB     | 2023/01/06 | 冯文     |

### BaseLine1（Pytorch FP32）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度           | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|--------------------|--------------|------------|----------|
| Eager单卡    | 24         | 129.66(samples/s)  | 23059MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 24         | 237.87(samples/s)  | 23225MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 24         | 406.88 (samples/s) | 23759MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 24         | 837.94 (samples/s) | 23687MiB     | 2023/01/06 | 冯文     |

### OneFlow（Graph FP16） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Graph单卡    | 24         | 216.09(samples/s) | 7945MiB      | 2023/01/06 | 冯文     |
| Graph单卡2卡 | 24         | 387.57(samples/s) | 8184MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 24         | 685.20(samples/s) | 8184MiB      | 2023/01/06 | 冯文     |
| Graph单机8卡 | 24         | 813.12(samples/s) | 15841MiB     | 2023/01/06 | 冯文     |

### OneFlow（Graph FP32） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Graph单卡    | 24         | 94.72(samples/s)  | 13337MiB     | 2023/01/06 | 冯文     |
| Graph单机4卡 | 24         | 177.14(samples/s) | 13702MiB     | 2023/01/06 | 冯文     |
| Graph单机4卡 | 24         | 323.60(samples/s) | 13702MiB     | 2023/01/06 | 冯文     |
| Graph单机8卡 | 24         | 671.28(samples/s) | 13694MiB     | 2023/01/06 | 冯文     |

### OneFlow（eager FP32）
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Eager单卡    | 24         | 89.71(samples/s)  | 15343MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 24         | 171.27(samples/s) | 17533MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 24         | 308.86(samples/s) | 17533MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 24         | 649.84(samples/s) | 17529MiB     | 2023/01/06 | 冯文     |

### BaseLine1（Pytorch FP16）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度            | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|---------------------|--------------|------------|----------|
| Eager单卡    | 16         | 213.53(samples/s)   | 13631MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 16         | 389.79(samples/s)   | 12981MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 16         | 639.89(samples/s)   | 14589MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 16         | 1252.12 (samples/s) | 15729MiB     | 2023/01/06 | 冯文     |

### BaseLine1（Pytorch FP32）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度           | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|--------------------|--------------|------------|----------|
| Eager单卡    | 16         | 126.55(samples/s)  | 17095MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 16         | 226.21(samples/s)  | 19259MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 16         | 356.12 (samples/s) | 18603MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 16         | 756.06 (samples/s) | 19243MiB     | 2023/01/06 | 冯文     |

### OneFlow（Graph FP16） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度           | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|--------------------|--------------|------------|----------|
| Graph单卡    | 16         | 209.86(samples/s)  | 5847MiB      | 2023/01/06 | 冯文     |
| Graph单卡2卡 | 16         | 353.85(samples/s)  | 6084MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 16         | 577.90(samples/s)  | 6086MiB      | 2023/01/06 | 冯文     |
| Graph单机8卡 | 16         | 1120.53(samples/s) | 6078MiB      | 2023/01/06 | 冯文     |

### OneFlow（Graph FP32） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Graph单卡    | 16         | 93.72(samples/s)  | 9261MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 16         | 169.02(samples/s) | 9626MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 16         | 293.69(samples/s) | 9626MiB      | 2023/01/06 | 冯文     |
| Graph单机8卡 | 16         | 611.34(samples/s) | 9616MiB      | 2023/01/06 | 冯文     |

### OneFlow（eager FP32）
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Eager单卡    | 16         | 88.65(samples/s)  | 11225MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 16         | 160.94(samples/s) | 12157MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 16         | 276.20(samples/s) | 12157MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 16         | 586.68(samples/s) | 12153MiB     | 2023/01/06 | 冯文     |

### BaseLine1（Pytorch FP16）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度           | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|--------------------|--------------|------------|----------|
| Eager单卡    | 8          | 155.68(samples/s)  | 7411 MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 8          | 257.39(samples/s)  | 7957 MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 8          | 382.35 (samples/s) | 7927 MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 8          | 717.39 (samples/s) | 7927MiB      | 2023/01/06 | 冯文     |

### BaseLine1（Pytorch FP32）
>使用代码： https://github.com/ccssu/GLM/tree/align_test_speed

| 模式         | batch-size | 训练速度           | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|--------------------|--------------|------------|----------|
| Eager单卡    | 8          | 119.01(samples/s)  | 9915 MiB     | 2023/01/06 | 冯文     |
| Eager单机2卡 | 8          | 185.78(samples/s)  | 9079 MiB     | 2023/01/06 | 冯文     |
| Eager单机4卡 | 8          | 251.66 (samples/s) | 8415 MiB     | 2023/01/06 | 冯文     |
| Eager单机8卡 | 8          | 508.88 (samples/s) | 9139 MiB     | 2023/01/06 | 冯文     |

### OneFlow（Graph FP16） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Graph单卡    | 8          | 188.91(samples/s) | 3743 MiB     | 2023/01/06 | 冯文     |
| Graph单卡2卡 | 8          | 278.21(samples/s) | 3978MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 8          | 407.16(samples/s) | 3986MiB      | 2023/01/06 | 冯文     |
| Graph单机8卡 | 8          | 720.74(samples/s) | 3978MiB      | 2023/01/06 | 冯文     |

### OneFlow（Graph FP32） 
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Graph单卡    | 8          | 89.43(samples/s)  | 5179MiB      | 2023/01/06 | 冯文     |
| Graph单机2卡 | 8          | 146.49(samples/s) | 5540MiB      | 2023/01/06 | 冯文     |
| Graph单机4卡 | 8          | 219.04(samples/s) | 5548MiB      | 2023/01/06 | 冯文     |
| Graph单机8卡 | 8          | 434.25(samples/s) | 5540MiB      | 2023/01/06 | 冯文     |

### OneFlow（eager FP32）
> 使用代码: https://github.com/Oneflow-Inc/one-glm `main分支`

| 模式         | batch-size | 训练速度          | 训练显存占用 | 完成时间   | 测试人员 |
|--------------|------------|-------------------|--------------|------------|----------|
| Eager单卡    | 8          | 80.88(samples/s)  | 6259MiB      | 2023/01/06 | 冯文     |
| Eager单机2卡 | 8          | 134.71(samples/s) | 6931MiB      | 2023/01/06 | 冯文     |
| Eager单机4卡 | 8          | 207.89(samples/s) | 6931MiB      | 2023/01/06 | 冯文     |
| Eager单机8卡 | 8          | 434.96(samples/s) | 6927MiB      | 2023/01/06 | 冯文     |

**Comment by wangguojim** [comment]
我这边评测也做不到线性增长，有损失，不知道是否是设置不对

**Comment by Lisa976** [comment]
请问一下跑GLM oneflow fp16推理最低的配置是什么，单机8卡 24G显存，将模型切分成8块，加载模型还是报out of memory
但是在原来DeepSpeed下跑GLM推理是ok的，请问oneflow是需要更多的显存来换取加速吗？ 

报错如下：
building GPT2 model ...
(mpu.get_data_parallel_rank() == 0)=True
 > number of parameters on model parallel rank 0: 9879633920
global rank 0 is loading checkpoint /data/nlp/one-glm-main/checkpoint/glm-10b chinese_MP8/80000/mp_rank_00_model_states.pt
(mpu.get_data_parallel_rank() == 0)=False
terminate called after throwing an instance of 'oneflow::RuntimeException'
  what():  Error: out of memory

**Comment by wangguojim** [comment]
已收到

**Comment by wangguojim** [comment]
已收到
